[package]
name = "bootloader_samv71"
version = "0.0.1"
authors = ["Bob Adams <bob@bobadams5.com>"]
edition = "2021"

[dependencies]
kernel     = { path = "../../../tock/kernel" }
samv71q21b = { path = "../../../tock/chips/samv71q21b" }
cortexm7   = { path = "../../../tock/arch/cortex-m7" }

bootloader = { path = "../../bootloader" }
